name: Build OlyntheOS ISO

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            debootstrap \
            squashfs-tools \
            xorriso \
            grub-pc-bin \
            grub-efi-amd64-bin \
            mtools \
            rsync \
            curl \
            wget

      - name: Make scripts executable
        run: chmod +x build.sh

      - name: Run build
        run: sudo ./build.sh

      - name: Upload ISO
        uses: actions/upload-artifact@v4
        with:
          name: OlyntheOS-ISO
          path: "*.iso"
